# This is a config for E2B sandbox template.
# You can use 'template_id' (raqk5tclshrjs75p9g1n) or 'template_name (reflex-e2b-poc) from this config to spawn a sandbox:

# Python SDK
# from e2b import Sandbox
# sandbox = Sandbox(template='reflex-e2b-poc')

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create({ template: 'reflex-e2b-poc' })

team_id = "460355b3-4f64-48f9-9a16-4442817f79f5"
memory_mb = 4_096
cpu_count = 4
dockerfile = "e2b.Dockerfile"
template_name = "reflex-e2b-poc"
template_id = "raqk5tclshrjs75p9g1n"
